name: Surf Check
on: 
  schedule:
  - cron: '55 */2 * * *'
  
  workflow_dispatch:

jobs:
  job1:
    name: Checking waves
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      with: { ref: automation }
    - name: List files
      run: ls
      
    - name: ğŸ Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: ğŸ’¿ Install pip packages
      run: pip install pandas arrow matplotlib scipy requests

    - name: ğŸš€ Run Automation
      run:  python swel.py   
      
    - name: Push to built branch
      uses: Automattic/action-commit-to-branch@master
      with:
        branch: 'automation'
        commit_message: 'Build master'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Required  
